/** @type {import('tailwindcss').Config} */
import withMT from "@material-tailwind/react/utils/withMT";

module.exports = withMT({
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        neutral: {
          0: "var(--Neutral0)",
          10: "var(--Neutral10)",
          100: "var(--Neutral100)",
          200: "var(--Neutral200)",
          300: "var(--Neutral300)",
          400: "var(--Neutral400)",
          500: "var(--Neutral500)",
          600: "var(--Neutral600)",
          700: "var(--Neutral700)",
          800: "var(--Neutral800)",
          900: "var(--Neutral900)",
          1000: "var(--Neutral1000)",
          1100: "var(--Neutral1100)",
          "100A": "var(--Neutral100A)",
          "200A": "var(--Neutral200A)",
          "300A": "var(--Neutral300A)",
          "400A": "var(--Neutral400A)",
          "500A": "var(--Neutral500A)",
        },
        darkNeutral: {
          10: "var(--DarkNeutral0)",
          100: "var(--DarkNeutral100)",
          200: "var(--DarkNeutral200)",
          250: "var(--DarkNeutral250)",
          300: "var(--DarkNeutral300)",
          350: "var(--DarkNeutral350)",
          400: "var(--DarkNeutral400)",
          500: "var(--DarkNeutral500)",
          600: "var(--DarkNeutral600)",
          700: "var(--DarkNeutral700)",
          800: "var(--DarkNeutral800)",
          900: "var(--DarkNeutral900)",
          1000: "var(--DarkNeutral1000)",
          1100: "var(--DarkNeutral1100)",
          "100A": "var(--DarkNeutral100A)",
          "200A": "var(--DarkNeutral200A)",
          "250A": "var(--DarkNeutral250A)",
          "300A": "var(--DarkNeutral300A)",
          "350A": "var(--DarkNeutral350A)",
          "400A": "var(--DarkNeutral400A)",
          "500A": "var(--DarkNeutral500A)",
          pitch: "var(--DarkNeutralPitch)",
          pitchA: "var(--DarkNeutralPitchA)",
        },
        blue: {
          200: "var(--Blue200)",
          300: "var(--Blue300)",
          400: "var(--Blue400)",
          500: "var(--Blue500)",
          600: "var(--Blue600)",
          700: "var(--Blue700)",
          800: "var(--Blue800)",
          900: "var(--Blue900)",
        },
        red: {
          200: "var(--Red200)",
          300: "var(--Red300)",
          400: "var(--Red400)",
          500: "var(--Red500)",
          600: "var(--Red600)",
          700: "var(--Red700)",
          800: "var(--Red800)",
          900: "var(--Red900)",
        },
        orange: {
          600: "var(--Orange600)",
          800: "var(--Orange800)",
        },
        yellow: {
          300: "var(--Yellow300)",
          400: "var(--Yellow400)",
          500: "var(--Yellow500)",
        },
        green: {
          200: "var(--Green200)",
          300: "var(--Green300)",
          400: "var(--Green400)",
          500: "var(--Green500)",
          600: "var(--Green600)",
          700: "var(--Green700)",
          800: "var(--Green800)",
          900: "var(--Green900)",
        },
        purple: {
          200: "var(--Purple200)",
          300: "var(--Purple300)",
          400: "var(--Purple400)",
          500: "var(--Purple500)",
          600: "var(--Purple600)",
          700: "var(--Purple700)",
          800: "var(--Purple800)",
          900: "var(--Purple900)",
        },
        mediumNeutral: "var(--MediumNeutral)",
        10121499: "var(--10121499)",
        navBg: "var(--navBg)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      backgroundColor: {
        btn_neutral: "var(--MediumNeutral)",
        btn_hover: "var(--DarkNeutral800)",
        boardHoverDark: "var(--Neutral1000)",
        boardHoverLight: "var(--DarkNeutral700)",
      },
      boxShadow: {
        overlay_light:
          "0px 1px 1px rgba(9, 30, 66, 0.25),0px 0px 1px rgba(9, 30, 66, 0.31)",
        overlay_dark:
          "0px 0px 0px rgba(0, 0, 0, 0),0px 1px 1px rgba(3, 4, 4, 0.5),0px 0px 1px rgba(3, 4, 4, 0.5)",
      },
      borderColor: {
        light: "var(--borderLight)",
        dark: "var(--borderDark)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
});
